import { ImageGroups } from "../../types";

export const imageGrpKeys: ImageGroups = {
  cards: {
    amusementPark: "",
    energyDrink: "",
    heartPhone: "",
    hospital: "",
    radioStation: "",
    simpleSolarPanel: "",
    simpleWindTurbine: "",
    superWindTurbine: "",
    superSolarPanel: "",
    stocksChart: "",
    toolStore: "",
  },
  emblems: {
    concrete: "",
    crystals: "",
    islandStats: "",
    metals: "",
    oilRig: "",
    townExpansion: "",
  },
  frames: {
    bamboo: "",
    greenLeaves: "",
    metal: "",
    rusty: "",
    stefani: "",
  },
  gameIcons: {
    activateGradient: "",
    angryFace: "",
    battery: "",
    blueLevelUpArrow: "",
    buildingsSpace: "",
    calendar: "",
    citizenCircular: "",
    citizensSpace: "",
    concrete: "",
    craftButton: "",
    crystals: "",
    dieselBarrel: "",
    energyProduction: "",
    energyUtilization: "",
    expenses: "",
    gold: "",
    greenWavyArrow: "",
    growth: "",
    happyFace: "",
    id: "",
    income: "",
    levelUpGradient: "",
    metals: "",
    neutralFace: "",
    overjoyedFace: "",
    rank: "",
    regSpace: "",
    sadFace: "",
    sellGradient: "",
    sideBarArrow: "",
    sliderBar: "",
    sliderDot: "",
    totalGold: "",
    user: "",
    woodenCloseModal: "",
  },
  labels: {
    colorful: "",
    goldenSpecial: "",
    goldenStandard: "",
    greenEnergy: "",
    level: "",
    rusty: "",
    woodenGround: "",
    woodenLong: "",
    woodenNormal: "",
    woodenShort: "",
  },
  maps: {
    townMap: "",
  },
  menus: {
    buildings: "",
    regs: "",
    sps: "",
  },
  modal_backgrounds: {
    amusementParkBG: "",
    dieselFactoryBG: "",
    hospitalBG: "",
    levelUpBuildingBG: "",
    levelUpRegBG: "",
    quarryConcreteBG: "",
    quarryCrystalsBG: "",
    quarryMetalsBG: "",
    quarryOilRigBG: "",
    radioStationBG: "",
    solarPanelBG: "",
    toolStoreBG: "",
    townExpansionBG: "",
    townHallBG: "",
    windTurbineBG: "",
  },
  onMapAssets: {
    REGPadlock: "",
    REGPlaceholder: "",
    REG__01: "",
    amusementPark: "",
    buildingPadLock: "",
    buildingPlaceholder: "",
    dieselFactory: "",
    forest_01: "",
    hospital: "",
    orange_Bush_and_Shadow_01: "",
    radioStation: "",
    simpleSolarPanel: "",
    simpleWindTurbine: "",
    superSolarPanel: "",
    superWindTurbine: "",
    toolStore: "",
    townHall: "",
    tree_01: "",
    tree_02: "",
    tree_03: "",
    tree_05: "",
    trees_and_Shadow_01_Big: "",
    trees_and_Shadow_01_Small: "",
  },
  quarries: {
    concreteIcon: "",
    crystalsIcon: "",
    metalsIcon: "",
    oilRigIcon: "",
  },
  townExpansion: {
    Emblem: "",
    Icon: "",
  },
  workers: {
    concrete: "",
    crystals: "",
    doctor: "",
    metals: "",
    oilRig: "",
    simpleCitizen: "",
  },
};
