services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: jimzord204/game-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: serve -s dist

  backend:
    image: jimzord204/web-server:latest
    ports:
      - "3500:3500"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3500
    command: npm start

  db:
    image: mysql:latest
    ports:
      - "3307:3306" # Change the host port from 3306 to 3307
    environment:
      MYSQL_ROOT_PASSWORD: __SuPeRSecretP@ssw0rd!__
      MYSQL_DATABASE: genera-game-v3
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/dev/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./sql/dev/2_init-data.sql:/docker-entrypoint-initdb.d/2_init-data.sql:ro

# This must be at the top level of the file
volumes:
  db-data: