# Use an official Node.js runtime as a parent image
FROM arm64v8/node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Install serve to serve the build
# RUN npm install -g serve

# Expose the port the app runs on
# I will be using Nginx to serve the build (port 3000)
EXPOSE 3000

# # Command to run the application
# CMD ["serve", "-s", "dist"]
